[jenkinsServer]
10.0.1.26

[appServer]
10.0.2.15

[all:children]
jenkinsServer
appServer

[jenkinsServer:vars]
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/debal.pem

[appServer:vars]
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/debal.pem
